server:
  port: 8090

spring:
  data:
    redis:
      host: 47.83.162.65
      port: 5379
      database: 0
      password: hnzadmin
  cloud:
    nacos:
      discovery:
        server-addr: 47.83.162.65:8848
        username: nacos
        password: nacos
