server:
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1 # -1 unlimited

spring:
  profiles:
    active: dev
  application:
    name: main-service

logging:
  level:
    root: info

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_empty
    banner: false
  mapper-locations: classpath*:/mapper/*.xml
