server:
  port: 8091

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
        username: nacos
        password: nacos
  rabbitmq:
    host: 127.0.0.1
    port: 5682
    username: hnz
    password: admin123
    virtual-host: wechat

minio:
    endpoint: http://127.0.0.1:9000
    fileHost: http://127.0.0.1:9000
    bucketName: wechat
    accessKey: minioadmin
    secretKey: minioadmin
