server:
  port: 8091

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.85.49.237:8848
        username: nacos
        password: nacos
  rabbitmq:
    host: 10.85.49.237
    port: 5672
    username: hnz
    password: admin123
    virtual-host: wechat

minio:
    endpoint: http://127.0.0.1:9000
    fileHost: http://127.0.0.1:9000
    bucketName: wechat
    accessKey: minioadmin
    secretKey: minioadmin
