server:
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1 # -1 unlimited

spring:
  profiles:
    active: dev
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
logging:
  level:
    root: info