server:
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1 # -1 unlimited

spring:
  profiles:
    active: dev
  application:
    name: wechat-gateway
logging:
  level:
    root: info

#blackIp:
#  continueCounts: 5
#  timeInterval: 15
#  limitTime: 30