server:
  port: 8098

spring:
  data:
    redis:
      host: 47.83.162.65
      port: 5379
      database: 0
      password: hnzadmin
  cloud:
    nacos:
      discovery:
        server-addr: 47.83.162.65:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          # 负载均衡
          uri: lb://auth-service
          predicates:
            - Path=/passport/**

        - id: file-service
          # 负载均衡
          uri: lb://file-service
          predicates:
            - Path=/file/**
        - id: main-service
          # 负载均衡
          uri: lb://main-service
          predicates:
            - Path=/main/**,/userinfo/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true