server:
  port: 8098

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 5379
      database: 0
      password: hnzadmin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
#        username: nacos
#        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          # 负载均衡
          uri: lb://auth-service
          predicates:
            - Path=/passport/**

        - id: file-service
          # 负载均衡
          uri: lb://file-service
          predicates:
            - Path=/file/**
        - id: main-service
          # 负载均衡
          uri: lb://main-service
          predicates:
            - Path=/main/**,/userinfo/**,/friendRequest/**,/friendship/**,/friendCircle/**,/comment/**,/chat/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

blackIp:
  timeInterval: 5
  continueCounts: 5
  limitTime: 10